### PR TITLE
Update to V2.11

### PR DESCRIPTION
**Pull request by rxm7706**
Updated to latest version available 
Rerendered the feedstock
Fixed the source repo
closes https://github.com/conda-forge/pyicu-feedstock/pull/46

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
Hi @cu8blank @maresb

Can you review and merge please. Thanks & Regards.

**Review by maresb — APPROVED** [review]

**Comment by maresb** [comment]
@rxm7706, LGTM. I do not have permissions to merge this. Only @cu8blank is authorized to do that.

It looks like they are falling a bit behind; we may need to ask core to add someone else as a feedstock maintainer. Would you be interested? (I'm a bad pick since I'm not proficient in C++.)

**Comment by rxm7706** [comment]
> It looks like they are falling a bit behind; we may need to ask core to add someone else as a feedstock maintainer. Would you be interested? (I'm a bad pick since I'm not proficient in C++.)

Hi @maresb, thank you. I will raise a request to conda-forge/admin be added as a maintainer if @cu8blank can't review and merge. I am not a C++ developer either, but I could do the basics for packaging / reviews, merges and help as much as possible.

**Comment by maresb** [comment]
@ocefpaf, would you be able to approve #49 for @rxm7706?

**Pull request merged**
